from ast import main

def error_4(*arh):
